### ISSUE TITLE
Landsat's `transform_stac_to_stac` fails when missing some expected assets

### ISSUE THREAD

**Issue by carioca-au** [stac-utils/stactools#101]
@gadomski I have changed the code and now we don't test the band or image anymore, instead, we get all the information from the first GeoTIFF image available.
Also, I fixed the test that previously was returning an error due to the fact that the first image wasn't accessible.

Could you please have a look, review, and merge that for me?

Any extra information, please let me know.

Thank you

PR=> https://github.com/stac-utils/stactools/pull/100

**Comment by gadomski** [comment]
Thanks, I'll put a review on that PR! I've updated the title of this issue to capture that it's subsuming two previous issues (#92 and #97).
