### ISSUE TITLE
Enable writing remote HREF links, but saving locally

### ISSUE THREAD

**Issue by lossyrob** [stac-utils/stactools#12]
There's a common use case where a STAC will be copied to a remote location as either RELATIVE_PUBLISHED or ABSOLUTE_PUBLISHED, and it would be convenient to write files locally before copying them to a remote location.

For instance, if you'll be serving an ABSOLUTE_PUBLISHED catalog at `https://example.com/catalog.json`, you may want to write out the STAC files locally that have all links valid for the final destination, and then use file copying to write those files from the local machine up to their final destination.

The goal of this issue is to add stactools CLI commands to allow for that use case to be easily accomplished.

**Comment by cholmes** [comment]
The route that would make sense to me is to have a 'publish location' option in `stac copy` or anywhere that takes a catalog type.

**Comment by volaya** [comment]
@lossyrob Is this something that can be done with the layout classes that have been recently added to pystac? Myabe having a layout strategy that uses the remote location passed by the user to resolve the self hrefs of catalog elements...

**Comment by matthewhanson** [comment]
Another use case here is that you want to copy them to a bucket, but then serve them through a CDN endpoint

**Comment by lossyrob** [comment]
I think the layout strategy could be used here - if you have a mapping from `parent_dir` to the remote location, you could use [CustomLayoutStrategy](https://github.com/stac-utils/pystac/blob/main/pystac/layout.py#L263) for this. We'd probably want to wrap that in stactools to be a more straightforward library call and also expose on the CLI via the copy, though I'm not sure what that interface should look like exactly

**Comment by cholmes** [comment]
Closing issue, as this got fixed with #175. Thanks @volaya!
