### ISSUE TITLE
Move all "new package" pull requests to their own repositories

### ISSUE THREAD

**Issue by gadomski** [stac-utils/stactools#134]
Here's what we've got:

- [x] https://github.com/stac-utils/stactools/pull/114 SPOT: This one is based on https://github.com/stac-utils/stactools/pull/113, so how exactly it gets integrated depends on the answer to #133.
- [x] https://github.com/stac-utils/stactools/pull/84 Sentinel-1: This one should be included in the core packages (IMO) and we should support @scottyhq with anything they need to get it ready to rock.
- [x] https://github.com/stac-utils/stactools/pull/54 MODIS: This one is a little old and a bit out of date, and it failed its last CI. Any input is welcome on whether we should freshen this one up and move it out, or just close it. Tagging in @pflickin as the PR author.

In general, we don't have any documentation or procedures for adding new "core" packages to `stactools-packages`, so as we move these PR's out we should develop those docs and procedures as well. For these repositories, I ~image~ imagine it'd go like:

- Extract the relevant commits and code into their own repository, using something like [this script](https://gist.github.com/gadomski/a0ab8d18f56ff34454d2ed890d234534) with modifications to checkout the correct branch.
- Either directly create a new repo in `stactools-packages`, or have the user create the repo in their own account.
- Get the repo passing CI against the latest stactools `v0.2`
- Open a PR against stactools that adds the package as a "core" package in the README. This would also count as a request to move the repository into `stactools-packages` if it wasn't already there.

**Comment by scottyhq** [comment]
> Sentinel-1: This one should be included in the core packages (IMO) and we should support @scottyhq with anything they need to get it ready to rock. Either directly create a new repo in stactools-packages, or have the user create the repo in their own account.

Thanks @gadomski . Fine by me if you move #84 over to stactools-packages/sentinel1, I'm hopeful that I can tackle final modifications next week.

**Comment by gadomski** [comment]
Done: https://github.com/stactools-packages/sentinel1. I'll close #84, but will note the discussion there is very good. I'll re-up a callout to #85 as the tracking issue for creating a common boundary function in `stactools.core`.

**Comment by gadomski** [comment]
Done:
- https://github.com/stactools-packages/modis
- https://github.com/stactools-packages/spot
- https://github.com/stactools-packages/sentinel1

They aren't passing CI, but they aren't "core" dataset packages yet so I reckon that's ok. We still need to document/formalize the procedure for becoming a core repository.
