### ISSUE TITLE
Enable stactools to work with STAC APIs

### ISSUE THREAD

**Issue by lossyrob** [stac-utils/stactools#15]
Currently stactools and the `stac` CLI only work with static catalogs. This issue marks the need for each command, where appropriate, to work with a STAC API endpoint. Each command will require thinking through how to interact with the STAC API to generate similar functionality, and deciding if the functionality can be baked into the existing command or needs it's own STAC API-specific command.

**Comment by gadomski** [comment]
@lossyrob would we consider this issue **wontfix** in favor of **pystac-client**? Or do we want to keep this open to track the possibility of using **pystac-client** instead of **pystac** for fetching items in **stactools**?

**Comment by lossyrob** [comment]
The original intent of this issue was to have a subpackage of stactools be what pystac-client has become, so I think the former point is spot on and we can close.
