### ISSUE TITLE
Enable mypy

### ISSUE THREAD

**Issue by gadomski** [stac-utils/stactools#155]
Static typing is good we and we should use it if we can.

**Comment by cuttlefish** [comment]
I don't want to derail, but I'm curious if anyone has tried any of the alternatives? Pyright, Pyre, Pytype, etc.
mypy is the only one I've used.

**Comment by gadomski** [comment]
PySTAC used pyright for a while: https://github.com/stac-utils/pystac/issues/381. Personally I agree with @duckontheweb's points:

> - Using pyright adds a Node.js/npm dependency to a project that is otherwise purely Python
> - mypy seems to be the stricter of the two type checkers, so it's not obvious to me that pyright is adding anything

Plus it's nice to align with our upstream. But good to consider for sure!
