### ISSUE TITLE
Should Jupyter be a dev dependency?

### ISSUE THREAD

**Issue by cuttlefish** [stac-utils/stactools#165]
There's an existing `docker/notebook` script to run a Jupyter notebook. I thought there was a `script/notebook` to match it, but there isn't.
The `docker/notebook` script doesn't work because Jupyter isn't listed in the dev dependencies.

Should we:
1. Remove `docker/notebook`
2. Add Jupyter as a dev dependency and add `script/notebook`
3. Create a separate docker image that includes Jupyter and use that in `docker/notebook`

There's some work going into the `stactools-packages` repos to add example Jupyter notebooks, so I don't really like the idea of removing it entirely.
I think 3 is likely adding unneeded complexity and also doesn't make it easy for non-Docker users to run notebooks.
I'm leaning towards option two but am open to suggestions (or alternatives I've missed).

**Comment by gadomski** [comment]
> Add Jupyter as a dev dependency and add script/notebook

This makes sense to me, 👍🏽.
