### ISSUE TITLE
public-datasets repo

### ISSUE THREAD

**Issue by geospatial-jeff** [stac-utils/stactools#17]
Work has been started in https://github.com/developmentseed/public-datasets by @vincentsarago and @kylebarron to create an end-to-end solution for indexing aws public datasets in a STAC API.  I propose that we merge the two projects into one to consolidate the code and to prevent creating the same catalogs in two slightly different ways.  Interesting enough, the structure and intent of the two projects are almost identical.

I won't pretend to know the best way to do this. I'm not an owner of either repo.  But wanted to create a space where we could discuss the possibility of merging the two.

**Comment by kylebarron** [comment]
To add my viewpoint: I'm totally onboard with merging the two projects. One of the things I think we've been focusing on in `public-datasets` is the ability to make a PDS STAC catalog without making millions of GET requests for individual metadata files on S3. Geometries won't be quite as precise as reading the valid pixels from the image, but it'll be much faster to make the catalog.

For Landsat that means making use of the `scene_list.gz` metadata file and inferring geometry from the WRS2 grid. For Sentinel 2, that means inferring scene geometry from MGRS tile-relative orbit combinations. (I'm cleaning this up but so far it looks highly accurate.)

**Comment by lossyrob** [comment]
Thanks for bringing this up! I agree it would be great to align the two projects.

> prevent creating the same catalogs in two slightly different ways

This is definitely something that stactools is intended to do - create a shared space where data transformations (specifically STAC-ification, and also COG-ification or other pertinent data format transformations) can be contributed, fixed, and used in both a python library and CLI. This lets anyone looking to convert dataset to STAC/COG/etc format to find the functionality in one place, and lets the many eyes of open source make sure the data we're all creating is correct.

I think the best way to approach this is to have a tight scope around stactools, so it can be used in many contexts and have a clear set of goals. Similar to how PySTAC is scoped to being a (almost)-zero dependency set of data classes for representing and working with STAC, I think stactools would best be scoped to a library and CLI that encapsulates common methods for working with STAC that might require heavier dependencies (e.g. fsspec), and dataset-specific subpackages that are focused on converting a specific data source into STAC and COGs (and maybe Zarr for some?)

What I think should be "out of scope" for this project is anything dealing with infrastructure, deployment, or running things at scale or continuously. These are important components that will hopefully have quality open source solutions, but I think is better for other projects to handle. For instance, I'm using stactools currently in a workflow on Azure to create STACs and COGs on Azure Batch, and all of those deployment/infrastructure concerns live in that other codebase. I plan on contributing any of the dataset transformation logic here, and then using that in the setup needed to accomplish specific tasks around creating and maintaining public datasets.

> For Landsat that means making use of the scene_list.gz metadata file and inferring geometry from the WRS2 grid. For Sentinel 2, that means inferring scene geometry from MGRS tile-relative orbit combinations. (I'm cleaning this up but so far it looks highly accurate.)

For example, this to me seems in-scope, in that there could be a library method and a CLI command in a `landsat` and `sentinel2` subpackage that has the library methods/CLI commands for inferring geometries from these sources, and generating a catalog from those. 

I'm definitely in favor of consolidating functionality between the projects, working together on adding dataset subpackages and ensuring we're all making the same valid STAC and COGs. If we can collectively decide on the boundaries of what should be in stactools vs in projects that use stactools in anger, the better we'll be able to know what goes where and maintain the common features over time.

What this could look like moving forward is to decide on and record the scope of stactools (in this issue or a dedicated issue, eventually with a PR to the README and docs), determine what parts of `public-datasets` would best be integrated into stactools and then do that integration work. In that scenario, any things out-of-scope from public-datasets would remain in that project, which would take a dependency on stactools.

**Comment by gadomski** [comment]
@kylebarron @lossyrob @geospatial-jeff is this issue still of use to ya'll?

**Comment by vincentsarago** [comment]
we didn't really pursue with public-datasets so I guess we can close this issue
