### ISSUE TITLE
`stac create-item` and associated API function

### ISSUE THREAD

**Issue by gadomski** [stac-utils/stactools#179]
**Describe the solution you'd like**
I think there's some boilerplate in "open a file in rasterio and create an Item from it". E.g. https://github.com/gadomski/alos-dem/blob/d4bbd4a7ed6d2d362626a829dff73fa1e6145d87/src/stactools/alos_dem/stac.py#L12-L32. It'd be nice to call `stactools.core.create_item(href)` and get back something as simple as possible. That'd include:
- geometry and bbox populated
- id from filename
- maybe the proj extension implemented if the thing's not in EPSG:4326
- asset w/ the original href

This would simplify standing up new dataset packages, and would be an equivalent to `rio info` for `stac`. Could even make the command called `stac info`?

**Describe alternatives you've considered**
Doing it myself all the time for lots of new datasets :-).

**Additional context**
I thought I remembered there being an issue for this already, but I couldn't find it after some quick Friday-afternoon searching. If there is feel free to close.

**Comment by cholmes** [comment]
I like this idea. Perhaps your confusion on an issue may be that there already is a command called `stac info`:

```
% stac info https://www.planet.com/data/stac/catalog.json
Catalog ID: planet
------------------
   CATALOGS: 3 
COLLECTIONS: 2 
      ITEMS: 9 (extensions: https://stac-extensions.github.io/projection/v1.0.0/schema.json,https://stac-extensions.github.io/view/v1.0.0/schema.json,https://stac-extensions.github.io/eo/v1.0.0/schema.json)
```

Though sounds like yours is to work at the item level? That'd be cool for sure.
