### ISSUE TITLE
Populate type signatures

### ISSUE THREAD

**Issue by cuttlefish** [stac-utils/stactools#183]
Ensure that the signatures to all 'stactools.{core|cli|testing}' functions/methods have type annotations.

See #155 and #182

**Comment by kylebarron** [comment]
Might also make sense to add `--check-untyped-defs` to the mypy config. If your functions are untyped mypy does nothing: https://mypy.readthedocs.io/en/stable/common_issues.html#no-errors-reported-for-obviously-wrong-code

Or if you want to slowly fix type errors, incrementally adding types to function definitions can be preferable

**Comment by cuttlefish** [comment]
Yeah, that sounds good. I'm playing with `MonkeyType`. There aren't a ton of signatures to add, so I think I'll tweak the generated ones and enforce more strict checking in the `mypy.ini` file.
