### ISSUE TITLE
Packages link includes PR images

### ISSUE THREAD

**Issue by gadomski** [stac-utils/stactools#200]
**Describe the bug**
The "Packages" link on the **stactools** Github page includes images from PR builds.

**Expected behavior**
I think the "Packages" link should include either:
1. Only versioned images (e.g. the v0.2.1 image), or
2. Both versioned images and a "latest" image built from **main**

**Screenshots and shell session dumps**
![Screen Shot 2021-09-13 at 10 59 21 AM](https://user-images.githubusercontent.com/58314/133126054-8a38e057-a077-4e61-8a02-5a4d08e7d39a.png)

**Comment by cuttlefish** [comment]
I don't think there's a way to filter which tags are displayed. I'll remove the PR builds.

**Comment by cuttlefish** [comment]
This will be resolved when #203 is completed (and I've manually deleted the existing images)

**Comment by gadomski** [comment]
> manually deleted the existing images

Done, closing.
