### ISSUE TITLE
Upgrade (or relax) GDAL requirement

### ISSUE THREAD

**Issue by gadomski** [stac-utils/stactools#215]
GDAL is up to v3.4, and our current version requirements require v3.3: https://github.com/stac-utils/stactools/blob/main/setup.cfg#L43. Two options:
1. We could just bump the minor version in the requirement, e.g. `gdal ~= 3.4.0`
2. We could relax the requirement to allow any minor version beyond v3.3, e.g. `gdal ~= 3.3`

My instinct is option 2 but interested of others have opinions.

**Comment by sgillies** [comment]
@gadomski this project hardly uses GDAL's python bindings at all, right? Why not drop the dependency? It looks to me like everything in https://github.com/stac-utils/stactools/blob/0e8952a68982246cce00f74bea4ba9a18ff16424/src/stactools/core/addraster.py#L30-L50 could be done between the rasterio and numpy APIs.

**Comment by gadomski** [comment]
> Why not drop the dependency?

Yup, I'm into this. We picked up the direct `GDAL` dependency a while back in #204 but it'd be good to remove. I'll take this on as a chore (#216).
