### ISSUE TITLE
Remove GDAL requirement

### ISSUE THREAD

**Issue by gadomski** [stac-utils/stactools#216]
As discussed in #215, GDAL and rasterio don't always play nicely together. Everything that we added in #204 could be done w/ rasterio, so we should move everything over to that and remove the GDAL dependency.

**Comment by sgillies** [comment]
@gadomski I can take this one on during my current sprint at work. It's highly related to https://github.com/rasterio/rasterio/issues/244#issuecomment-928542575. I think my approach will be to copy the rio-calc chunker in here to provide efficient statistics computation.

Additionally https://github.com/stac-utils/stactools/blob/0aa483dd7b5b9891cab3839d12c7df4d9037703d/src/stactools/core/utils/convert.py#L9 could be rewritten to not use gdal_translate. Without requiring conda it's not possible for a Python package to specify that it depends on a program in a non-Python package. Maybe that's a different issue?

**Comment by gadomski** [comment]
> Without requiring conda it's not possible for a Python package to specify that it depends on a program in a non-Python package. Maybe that's a different issue?

Yeah, I guess we've been implicitly relying on being in a geo-enabled box so GDAL stuff is available, but I agree that removing that implicit dependency (and the command-line callout) would be preferable.

**Comment by geospatial-jeff** [comment]
Could rewrite `cogify` to use https://github.com/cogeotiff/rio-cogeo

**Comment by gadomski** [comment]
@geospatial-jeff we really aren't doing anything special in the `cogify` function (other than defaulting to `deflate` compression). Might make sense to remove it all together and just use **rio-cogeo** in any downstream packages that need to cogify? I'm not sure what the value of having a `cogify` function in **stactools** is, if there's a Python API already out there.
