### ISSUE TITLE
Relax upper bounds on dependencies

### ISSUE THREAD

**Issue by TomAugspurger** [stac-utils/stactools#227]
Currently, all the stactools dependencies are set as `~=` dependencies: https://github.com/stac-utils/stactools/blob/4a19089454fbe2a6148bf6e062a7f9393c636ca9/setup.cfg#L33-L42. Would folks be OK with removing those upper bounds?

For some packages that follow calver, like `fsspec`, that kind of constraint isn't meaningful. There's no reason to pin to a specific month's release.

It's also not meaningful for packages that use `x.y.z` version numbers, but don't actually promise to follow semver. I haven't checked if all those libraries declare that they do.

I also don't think it's appropriate for a "base" library like stactools to setup upper bounds. What if a downstream package requires a higher version of a package than what's allowed here?

And finally, IMO it's almost never appropriate for a library to declare an upper bound. Who's to say that stactools isn't compatible with the next release of that package? https://iscinumpy.dev/post/bound-version-constraints/ goes into this in much more detail, but the short version is that it's best for libraries to be as flexible as possible and let specific applications to pin their dependencies as they desire.

**Comment by TomAugspurger** [comment]
👍 thanks.

One workflow question around testing: IME it's best to have 2-3 environments:

1. An "earliest" / "oldest" environment with the minimum required dependencies for each library. This would match the lower bounds in the `setup.cfg`
2. A "latest" / "newest" environment, that's either unpinned or pinned to the latest version + Dependabot to auto-upgrade when new packages are available. My preference is just for not pinning; We might have the occasional failure from an incompatible upgrade, but IMO that's OK.
3. (maybe) An "upstream-dev" environment, that tests against unreleased versions of critical dependencies (maybe just pystac?).

Are folks OK with that rough that?

**Comment by gadomski** [comment]
Sounds good to me, couple of questions/thoughts:
- How do you go about specifying **1**? Do you freeze a "minimum required" `requirements.txt`?
- I think **3** should include **rasterio** as well as **pystac** as a `--pre` install.

**Comment by TomAugspurger** [comment]
> How do you go about specifying 1? Do you freeze a "minimum required" requirements.txt?

Yeah, either a requirements file or pinned versions in the CI job that's building that environment.
