### ISSUE TITLE
Incorporate `stac-check`

### ISSUE THREAD

**Issue by gadomski** [stac-utils/stactools#230]
**Is your feature request related to a problem? Please describe.**
We've had halting support for using upstream validators as a part of the **stactools** cli, e.g. #191 and #151. There's probably space for taking a step back and making the `stac validate` story a bit more coherent, but as an incremental improvement we could include the new https://github.com/jonhealy1/stac-check project.

**Describe the solution you'd like**
Add a `stac lint` command, e.g.:

```shell
stac lint simple-item.json
```

This could include a `--recursive` option to lint an entire tree.

**Describe alternatives you've considered**
There could(/should) be a higher-level `stac validate` command that includes linting. There's also some common "take this STAC catalog and report on it" architecture common between `stac info`, `stac validate`, and ??? that could be refactored.

**Additional context**
None

**Comment by jonhealy1** [comment]
I have made a draft pr. I have added a lint option to the cli. I have also added the basic STAC best practices warning messages from https://github.com/jonhealy1/stac-check. I could add some of the validation messaging I use too if wanted, which mostly comes from the stac-validator project.

**Comment by gadomski** [comment]
This is great! I dropped an initial review on #254 with a couple of notes.

Since `stac-check` will bring in `stac-validator` as a dependency, I think it will make sense to switch the [stactools validation command](https://github.com/stac-utils/stactools/blob/5419c61d6f4b357d7038d145c19efa92eccbc9e4/src/stactools/cli/commands/validate.py) to use `stac-validator`. That doesn't have to happen in #254, I'm happy to do it myself in a follow-on PR.

Thanks again for the contribution, `stac-check` looks like a great tool!
