### ISSUE TITLE
datalad vs. stactools

### ISSUE THREAD

**Issue by mankoff** [stac-utils/stactools#249]
This is a repost of the same question asked abotu EODAG at https://github.com/CS-SI/eodag/discussions/409 . I will not be asking this question elsewhere until some time has passed, depending on responses here and at EODAG.

I've just discovered STAC, and the stactools tool as an implementation of the STAC spec. I was working on a data meta-portal (not a meta-data portal) using datalad https://www.datalad.org/ (built on git annex). datalad and stactools seem similar, but I'm new enough to not fully understand either. Can anyone here provide some insight into pros/cons of datalad vs. stacools, complementary or divergent use cases, etc.?

The first/biggest difference I see is that STAC requires rasters or point clouds (but not vector data?) while datalad is data agnostic. It is built on git-annex, and works with any remote binary blob.

I believe this is better posted under "discussions" but that is not turned on for this repository.

**Comment by gadomski** [comment]
> stactools tool as an implementation of the STAC spec

[PySTAC](https://github.com/stac-utils/pystac) is the actual Python implementation of the STAC specification -- **stactools** is just a higher-level utility package (and namespace) to do more complex operations with STAC catalogs.

> Can anyone here provide some insight into pros/cons of datalad vs. stacools (sic), complementary or divergent use cases, etc.?

I don't really know much about datalad, so I'm not a great person to do a compare/contrast.

> The first/biggest difference I see is that STAC requires rasters or point clouds (but not vector data?) while datalad is data agnostic.

A STAC [Asset](https://github.com/radiantearth/stac-spec/blob/master/item-spec/item-spec.md#asset-object) can point to any data, but you're correct that the majority of use-cases for STAC up to this point have been raster-based (and to a limited extent, point cloud). However, this is some interesting work to extend STAC to other domains, e.g. [machine learning](https://github.com/stac-extensions/ml-aoi).

> I believe this is better posted under "discussions" but that is not turned on for this repository.

The [stac-spec repository has the primary Github discussion forum for the STAC ecosystem](https://github.com/radiantearth/stac-spec/discussions).

**Comment by mankoff** [comment]
Thanks. I discovered STAC from your recent re-Tweet about STAC support in QGIS. I will post my question over on the stac-spec repository, that seems like a more appropriate place.
