### ISSUE TITLE
stactools fails to install in py 3.9 and 3.10 b/c of rasterio 1.2.x

### ISSUE THREAD

**Issue by philvarner** [stac-utils/stactools#264]
**Describe the bug**
in a py 3.9 env, running `pip install stactools` fails to install

**To reproduce**

pip install stactools

```
      rasterio/_base.c:48560:19: error: implicit declaration of function '_PyGen_Send' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
                  ret = _PyGen_Send((PyGenObject*)yf, value == Py_None ? NULL : value);
```

issue is described here: https://github.com/rasterio/rasterio/issues/2333

updating to a rasterio 1.3 alpha version will likely resolve this.

**Expected behavior**

stactools installs successfully, as it does in py 3.8

**Screenshots and shell session dumps**

n/a

**Additional context**

FYI, install on a macOS M1 machine if this doesn't repro other Intel py 3.9/10 env.

**Comment by gadomski** [comment]
> FYI, install on a macOS M1 machine if this doesn't repro other Intel py 3.9/10 env.

Do you have a link describing why 3.9 fails on M1? Is it just lack of wheels? I don't see 3.9 referenced in any of the links in that issue.

**Comment by philvarner** [comment]
I don't know if it's specifically M1 -- I just thought to mention that since it's always a suspect now. 

Have you successfully run this on a 3.9 install?

**Comment by gadomski** [comment]
Yeah, from my local system:

```shell
$ mkvirtualenv stactools-264 >/dev/null 2>&1 && python --version && pip install stactools >/dev/null 2>&1
Python 3.9.12
$ python -c "import stactools.core; print(stactools.core.__version__)"
0.3.0
```

**Comment by philvarner** [comment]
what version of rasterio is installed?

**Comment by gadomski** [comment]
```shell
$ python -c "import rasterio; print(rasterio.__version__)"
1.2.10
```
