### ISSUE TITLE
Add test matrix against python 3.10 in CI

### ISSUE THREAD

**Issue by philvarner** [stac-utils/stactools#270]
3.10 is an allowed by setup.cfg for this package, but tests aren't run against it. This should be added to the test matrix. 

A couple of details on that:

1. The test versions need to be quoted as strings (e.g., "3.10") rather than be float values, or you'll get python version 3.1 instead of 3.10
2. rasterio 1.2.x doesn't work with python 3.10, so 1.3.0 needs to be installed explicitly with:

```
      - name: install rasterio 1.3a3 if python 3.10
        if: matrix.python-version == '3.10'
        run: pip install rasterio==1.3a3
```

There should also be a note about needing to do this in your project if using stactools with 3.10.

**Comment by gadomski** [comment]
If we need a pre-release of `rasterio` to get 3.10 to work, I'd think I'd be more inclined to remove 3.10 support from `setup.cfg`.

**Comment by gadomski** [comment]
> I think we should run the tests against 3.10 + rasterio 1.3.x, even if we restrict it to 3.9.

👍🏽 

> it's okay to advertise it with the caveat that you have to explicitly install the pre-release

Yeah, looking at `setup.cfg` we don't set any `python_requires`, but we do have metadata entries for 3.7, 3.8, and 3.9 (not 3.10). I think this aligns with what you're describing -- maybe we just add a "Python 3.10" section to the README describing the steps to install on 3.10, and call it good?

**Comment by philvarner** [comment]
yes, i was thinking adding `python_requires>=3.7` (or 3.8 if we just want to say we're doing that for 0.4.0) and add that readme section.
