### ISSUE TITLE
TestData: Caching for compressed files doesn't work

### ISSUE THREAD

**Issue by m-mohr** [stac-utils/stactools#367]
**Describe the bug**
It looks like caching + compress doesn't work at the same time.

To be able to read cached files, it seems the key of the external data dict needs to be the name of the zipped file, but then get_external_data always returns the path to the zipped file instead of the extracted file.

**To reproduce**

Manually download the zipped files and place them in the corresponding directory.
Unless they key of the external data dict is the name of the ZIP file, caching doesn't work for me.
But then I don't have a clue how the name of the file in the ZIP file is.

**Expected behavior**

Caching for compressed file works. I think `get_external_data` should always return the path of the extracted file.

**Additional context**

#364

**Comment by jsignell** [comment]
After rewriting the documentation in #451 I think this is maybe not an issue. I think it maybe works as expected but the behavior just wasn't well described. I'll leave this open so you can see what you think.

**Comment by m-mohr** [comment]
It's been quite some time and I'm not working with it anymore. Good documentation is good enough for now, thanks. :-)
