### ISSUE TITLE
Convert pointcloud .las to STAC

### ISSUE THREAD

**Issue by cholmes** [stac-utils/stactools#44]
It'd be great to have a stactool that can convert from a pointcloud in the las format to a STAC item. And perhaps a way to handle a directory of point clouds and convert that to a catalog. May also be interesting to have an explicit 3dep one, if it has particular metadata.

**Comment by gadomski** [comment]
https://github.com/stactools-packages/pointcloud has been created, but is not yet a "core package." We don't have a procedure to onboard new core packages, #140 outlines some of the considerations. Once those are resolved, we should try to onboard `pointcloud`.

**Comment by gadomski** [comment]
"Core packages" never really took off, so closing as OBE.
