### ISSUE TITLE
Add logic to utilize MTL file in landsat subpackage

### ISSUE THREAD

**Issue by lossyrob** [stac-utils/stactools#48]
#23 adds a command to migrate and fixup the collection 2 STAC for Landsat 8 (thank you Alex!)

The usage of MTL and other sidecar files is still unimplemented. There's a lot of [great discussion here](https://github.com/stac-utils/stactools/pull/23/files#r554131019) about the challenges and potential for MTL conversion.

This issue is to determine the need and potential for using the MTL and other files to derive STAC data for landsat; if we should, implement it, and if it's not a good choice, remove the MTL codepath in the subpackage.

**Comment by gadomski** [comment]
Migrated to https://github.com/stactools-packages/landsat/issues/1.
