### ISSUE TITLE
Add more file extension fields to Planet output

### ISSUE THREAD

**Issue by cholmes** [stac-utils/stactools#55]
It'd be good to make use of at least some of the [file](https://github.com/radiantearth/stac-spec/tree/dev/extensions/file) extension fields in Planet output. Most of these will be new for RC1, so may need pystac improvements to be able to do them.

Top ones to use I think are: data_type, size and nodata. I'm not sure exactly how to calculate them. It might be useful to try to do more of the fields too, like bits_per_sample, byte_order, checksum...

The fields could also be interesting for the UDM, but I'll put that in its own issue.

**Comment by gadomski** [comment]
Migrated to https://github.com/stac-utils/stactools/issues/55.
