### ISSUE TITLE
Better description of UDM in Planet conversion / output.

### ISSUE THREAD

**Issue by cholmes** [stac-utils/stactools#56]
The new [file](https://github.com/radiantearth/stac-spec/tree/dev/extensions/file) extension has an example of using a [mapping object](https://github.com/radiantearth/stac-spec/tree/dev/extensions/file#mapping-object) to describe a cloud cover mask. Seems like it'd be useful to include that information about Planet's cloud mask.

Info at https://developers.planet.com/docs/data/udm-2/ - hrm, it looks like we use one band per class, instead of one band with all classes in it, so perhaps it'd be better to describe it with a 'bands' object, even if there are no common names. Regardless, it'd be good to have more description of the UDM asset in STAC.

**Comment by cholmes** [comment]
Note there have been people who have made single band UDM from Planet's multi-band asset. Could be cool to give an option in planet STAC conversion to reformat into that (arguably) more useful option. Especially if we make a 'band' description for UDM / QA like https://github.com/radiantearth/stac-spec/issues/977

**Comment by gadomski** [comment]
Migrated to https://github.com/stactools-packages/planet/issues/3.
