### ISSUE TITLE
Missing core dependency on pyproj

### ISSUE THREAD

**Issue by TomAugspurger** [stac-utils/stactools#62]
pyproj is imported in stactools.core: https://github.com/stac-utils/stactools/blob/c9f82edfa5f0b29fd7a7cceb619c65f0adfd1d82/stactools_core/stactools/core/projection.py#L4.

However, I don't think that it's declared in the requirements file (I think https://github.com/stac-utils/stactools/blob/c9f82edfa5f0b29fd7a7cceb619c65f0adfd1d82/stactools_core/requirements.txt is the one).

Should it be a dependency? Or should we avoid using it in core?

**Comment by lossyrob** [comment]
That method moved to core and the refactor must not have added the
requirement (the file you stated is the right one). Pyproj is a pretty core
geospatial library, so I think it is good to depend on in stactools_core
and should be declared in the requirements.

**Comment by gadomski** [comment]
Fixed in 301da9a215afbdb7fe407482411e86739d795615.
