### ISSUE TITLE
Using the blue band to set Proj information for Landsat won't work with ST STAC files

### ISSUE THREAD

**Issue by alexgleith** [stac-utils/stactools#66]
https://github.com/stac-utils/stactools/blob/9ad65fde3bc56a5a8713fcc20fffeb0ea7cc3a56/stactools_landsat/stactools/landsat/utils.py#L103

The above line should try B10 if B2 is not available, and bail out if neither are there.

**Comment by lossyrob** [comment]
Closed by #67
