### ISSUE TITLE
Add linting various use-cases

### ISSUE THREAD

**Issue by TomAugspurger** [stac-utils/stactools#70]
Over in stac-vrt, we rely on the presence of some extensions to efficiently build VRTs from STAC metadata. This issue is a request for two things

1. Write a tool (CLI) to check that a STAC item contains the extended data needed by stac-vrt.
2. Verify that the STAC items generated by `stactools` include the extended data (as a linting check, that can optionally be skipped when it's not applicable / desired for whatever reason).

https://stac-vrt.readthedocs.io/en/latest/#building-stac-vrt-compatible-stac-items has the list of items currently required by stac-vrt.

**Comment by gadomski** [comment]
We have `stac validate` now, so that would be a nice place to add in warnings e.g. these two.

**Comment by gadomski** [comment]
Going to close this as OBE due to [stac-validator](https://github.com/stac-utils/stac-validator) and [stac-check](https://github.com/stac-utils/stac-check).
