### ISSUE TITLE
Include reflectance coefficients and license information

### ISSUE THREAD

**Issue by cholmes** [stac-utils/stactools#76]
For Planetscope data we include an XML metadata file that is mostly redundant information, but does include two interesting and useful pieces:

* Reflectance coefficients, per band. We need to figure out the structure in eo:bands for where to put per band information, but once we do we should add it.
* License information - the xml file seems to have a link to the actual license text, so we should make use of that in the license link.

**Comment by gadomski** [comment]
Moved to https://github.com/stactools-packages/planet/issues/2.
