### ISSUE TITLE
Add Sentinel 1 subpackage

### ISSUE THREAD

**Issue by scottyhq** [stac-utils/stactools#82]
I'd love to get a STAC catalog generated for the Sentinel-1 RTC public dataset covering CONUS in AWS https://registry.opendata.aws/sentinel-1-rtc-indigo/ 

I put together the framework for this over in the stac-sentinel repo, but it seems like the current recommendation is to add a submodule here:
https://github.com/stac-utils/stac-sentinel/pull/1#issuecomment-801660252 

I'm thinking of trying to follow the `sentinel2` subpackage closely. For starters this would just cover the RTC dataset, but there are others out there that could likely be added later (e.g. GRD, SLCs https://registry.opendata.aws/sentinel-1/). Doesn't seem like anyone else is actively working on this right @matthewhanson @lossyrob ?

**Comment by lossyrob** [comment]
@scottyhq I don't believe anybody is actively working on this; we'll need to generate STAC for Sentinel 1 GRD products in the next few months, and would gladly contribute to the subproject if you got it rolling!

Following the sentinel 2 package is a good idea - I've made some changes to it over in #83, which I'm aiming to merge this week. That and landsat (after that PR) should give some solid starting points.

**Comment by gadomski** [comment]
Closed by https://github.com/stac-utils/stactools/pull/84, moved to https://github.com/stactools-packages/sentinel1.
