### ISSUE TITLE
Failing to transform stac 0.7 to 1.0

### ISSUE THREAD

**Issue by carioca-au** [stac-utils/stactools#97]
The process was failing due neither B10 nor B2 were found within Landsat 5 stac.
The issue is addressed in the following PR, which adds B6 as a fallback to B10.
https://github.com/stac-utils/stactools/pull/96

As soon as this change is added to a new version, 0.1.5 I suppose, I'll be adding it to our project.

Thank you for your attention and time.

**Comment by carioca-au** [comment]
Good Afternoon @gadomski 

After reviewing what specifically the code was doing and why it was trying to use the **TIF** files, I realised that actually, we don't need to point a file, as any of the **TIF** files could provide the information that we need.
The new PR is :
https://github.com/stac-utils/stactools/pull/99

**Comment by gadomski** [comment]
Thanks! We'll take a look. Can #92 be closed as a duplicate of this issue?

**Comment by carioca-au** [comment]
It'll be created a new PR removing fallbacks and retrieving from any geotiff file the necessary information. 
Thank you
